### PR TITLE
Add new resources jquery-ui, jquery-tablesorter

### PR DESCRIPTION
**Pull request by Hedonil**
jquery-ui
Source: http://jqueryui.com/
Version: 1.11.1
License: jQuery projects are released under the terms of the MIT license.

jquery-tablesorter
Source: http://tablesorter.com/docs/
Version: 2.0.5
Licence: Dual licensed under MIT or GPL licenses

### CODE REVIEW

**Comment by Krinkle** [comment]
Please remove the `.svn` directories.

**Comment by Hedonil** [comment]
Completely removed both dev resources: test/ and build/

**Comment by Hedonil** [comment]
Also removed all leftover .svn's in other directories

**Comment by Krinkle** [comment]
Look at the git diff. These's still a bunch left:

```
res/jquery-tablesorter/2.0.5/addons/pager/.svn/all-wcprops
...
res/jquery-tablesorter/2.0.5/docs/assets/.svn/prop-base/ajax-content.html.svn-base
...
res/jquery-tablesorter/2.0.5/docs/css/.svn/all-wcprops
res/jquery-tablesorter/2.0.5/docs/css/.svn/entries
res/jquery-tablesorter/2.0.5/docs/css/.svn/text-base/jq.css.svn-base
...
res/jquery-tablesorter/2.0.5/themes/blue/.svn/text-base/style.css.svn-base
...
res/jquery-tablesorter/2.0.5/themes/green/.svn/text-base/style.css.svn-base
...
```

**Comment by Hedonil** [comment]
OK. 3rd take now.

**Comment by Krinkle** [comment]
It still doesn't make sense. Can you provide direct urls to where this comes from? There seem to be a ton of spurious files that aren't relevant to the distribution of the library. Most of these files don't belong on `static`. Only the actual distribution and license files should be needed.

I know you cleaned up the svn files in the follow-up, but it worries me because none of the official download distributions of jQuery UI or tablesorter have any svn stuff, so where did that come from? As it is, the files in this commit don't match any verifiable release version. They're from some unknown source and manually composed.

**Comment by Hedonil** [comment]
Well, 
- jquery-ui seems to be no problem, it's a direct download from http://jqueryui.com/resources/download/jquery-ui-1.11.1.zip
- tablesorter is a download from http://tablesorter.com/docs/#Download
  http://tablesorter.com/__jquery.tablesorter.zip
  The "core-files" are
- jquery.tablesorter.min.js
- jquery.tablesorter.js
- sort-icons in themes/  (optional)
- jquery.metadata.js (optional)

docs/ could be removed completely

**Comment by Hedonil** [comment]
As can see now in  https://github.com/christianbach/tablesorter   the __jquery.tablesorter.zip seesm to be an older version with "svn-crap".
I think I'm going to cancel this pull request and submit a fresh one with tablesorter from current github, without  docs/ & build/  directories

**Pull request closed without merging**
